video_source: 0
model_path: best(2).pt
frame_width: 640
frame_height: 480
line_outer: 150
line_inner: 350
line_range: 10
conf_threshold: 0.5
min_frames: 5
min_box_area: 500
tracker_config: bytetrack.yaml
log_file: people_counts.log
fps_display: true